import { ReactNode } from "react";
import { Metadata } from "next";
import Footer from "components/Footer";
import Nav from "components/Nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Food Delivery",
  description: "Food delivery app generated by create next app.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Nav />
          <main className="flex flex-row container">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
