import { ReactNode } from "react";
import { Metadata } from "next";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Food Delivery",
  description: "Food delivery app generated by create next app.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col h-full">
        <Navbar />
        <main className="flex flex-row flex-1 overflow-hidden gap-x-2 container">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
