import { ReactNode } from "react";
import { Metadata } from "next";
import Footer from "components/Footer";
import Nav from "components/Nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Food Delivery",
  description: "Food delivery app generated by create next app.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-full">
          <Nav />
          <main className="flex flex-row flex-1 overflow-hidden gap-x-2 container">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
